### ISSUE TITLE
Virtual Instance bug when using interface types as function return

### ISSUE THREAD

**Issue by daviddev16** [daviddev16/dependency4j#7]
## Expected Behavior

When using an abstract/interface as a function return type, the type should be appended to the search tree and no exception should be thrown.

## Actual Behavior

While using interfaces as return type:

```java
@Virtual
public Encoder md5Enconder() {
  return new MD5Encoder();
}
```

`DependencySearchTree#createTypeFamiliesInSearchTree` throw an error:

```java
Exception in thread "main" io.github.dependency4j.exception.InstallationFailedException: Package "com.example" installation failed.
	at io.github.dependency4j.DependencyManager.installPackage(DependencyManager.java:91)
	at io.github.dependency4j.DependencyManagerChainBuilder.installPackage(DependencyManagerChainBuilder.java:25)
	at com.example.Main.main(Main.java:26)
Caused by: java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "superclassClassType" is null
	at io.github.dependency4j.DependencySearchTree.generateSuperclassPathSet(DependencySearchTree.java:287)
	at io.github.dependency4j.DependencySearchTree.createSuperclassTreeMapping(DependencySearchTree.java:256)
	at io.github.dependency4j.DependencySearchTree.createTypeFamiliesInSearchTree(DependencySearchTree.java:139)
	at io.github.dependency4j.DependencySearchTree.lambda$createVirtualSingletonsInSearchTree$0(DependencySearchTree.java:337)
	at io.github.dependency4j.util.ReflectionUtil.consumeAllVirtualMethodsFromClassType(ReflectionUtil.java:43)
	at io.github.dependency4j.DependencySearchTree.createVirtualSingletonsInSearchTree(DependencySearchTree.java:333)
	at io.github.dependency4j.DependencySearchTree.createTypeFamiliesInSearchTree(DependencySearchTree.java:144)
	at io.github.dependency4j.DependencySearchTree.createTypeFamiliesInSearchTree(DependencySearchTree.java:100)
	at io.github.dependency4j.DependencySearchTree.insert(DependencySearchTree.java:52)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.dependency4j.DependencyManager.installPackage(DependencyManager.java:87)
	... 2 more

```

## Steps to Reproduce the Problem

  1. An example can be replicated by using interface as a return type.

## Specifications

  - Version: 1.0.4
  - JDK: Eclipse Adoptium 17.0.8.101

**Comment by daviddev16** [comment]
Fixed in 1.0.41
